# Generated by Django 3.0.3 on 2020-05-20 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tmsuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('m3_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('temp_alarm_max', models.IntegerField(default=0)),
                ('temp_alarm_min', models.IntegerField(default=0)),
                ('hum_alarm_max', models.IntegerField(default=0)),
                ('hum_alarm_min', models.IntegerField(default=0)),
                ('vib_alarm_max', models.IntegerField(default=0)),
                ('vib_alarm_min', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmsuser.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('temp_me', models.FloatField()),
                ('temp_avg', models.FloatField()),
                ('hum_min', models.FloatField()),
                ('hum_max', models.FloatField()),
                ('hum_me', models.FloatField()),
                ('hum_avg', models.FloatField()),
                ('vib_min', models.FloatField()),
                ('vib_max', models.FloatField()),
                ('vib_me', models.FloatField()),
                ('vib_avg', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status_desc', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.Product')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.User'),
        ),
    ]
